services:
    laravel.test:
        # build:
        #     context: ./docker/8.4
        #     dockerfile: Dockerfile
        #     args:
        #         WWWGROUP: '${WWWGROUP}'
        container_name: myflix-app
        image: sail-8.4/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-9000}:80'
            - '${VITE_PORT:-6173}:5173'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
            - '/mnt/brutus:/var/www/html/storage/app/public/nas'
            - '/home/fabio/projects/baron/database:/baron-database:ro'
        networks:
            - sail
        depends_on:
            - meilisearch
            - redis
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        container_name: myflix-meilisearch
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7701}:7700'
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
        volumes:
            - 'sail-meilisearch:/meili_data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://127.0.0.1:7700/health'
            retries: 3
            timeout: 5s
    redis:
        container_name: myflix-redis
        image: "redis:alpine"
        ports:
            - "${FORWARD_REDIS_PORT:-6380}:6379"
        volumes:
            - "sail-redis:/data"
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    whisper-api:
        build: ./whisper-api
        container_name: whisper-api
        volumes:
            - ./audio:/audio
        environment:
            - MODEL=large
        ports:
            - "5002:5001"
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-meilisearch:
        driver: local
    sail-redis:
        driver: local
